# -*- coding: utf-8 -*-
"""EKG simulator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1absoI0dglKNhv462Avt4yE9GE4_Xb5mP
"""

!pip install plotly

import numpy as np
import plotly.graph_objects as go

# ============================================================
# COORDINATE SYSTEM
# ============================================================
# X = right-left
# Y = anterior-posterior
# Z = superior-inferior
#
# Frontal plane   -> Y = 0
# Horizontal plane-> Z = 0
#
# Positive Z = superior
# Negative Z = inferior
# Positive Y = anterior

# ============================================================
# LEAD DEFINITIONS
# ============================================================

def frontal_lead(angle_deg):
    a = np.deg2rad(angle_deg)
    return np.array([-np.cos(a), 0.0, np.sin(a)])


def chest_lead(x, y, z):
    v = np.array([x, y, z], dtype=float)
    return v / np.linalg.norm(v)


# ============================================================
# LIMB LEADS (HEXAXIAL SYSTEM)
# ============================================================

lead_vectors = {
    "I":   frontal_lead(0),
    "II":  frontal_lead(-60),
    "III": frontal_lead(-120),
    "aVF": frontal_lead(-90),
    "aVL": frontal_lead(30),
    "aVR": frontal_lead(150),
}

# ============================================================
# PRECORDIAL LEADS (APPROXIMATION)
# ============================================================

precordial_vectors = {
    "V1": chest_lead(-0.55, 0.85,  0.05),
    "V2": chest_lead(-0.35, 0.90,  0.05),
    "V3": chest_lead(-0.10, 0.95,  0.00),
    "V4": chest_lead( 0.20, 0.95, -0.05),
    "V5": chest_lead( 0.45, 0.85, -0.05),
    "V6": chest_lead( 0.65, 0.75,  0.00),
}

lead_vectors.update(precordial_vectors)

# ============================================================
# NORMALIZATION
# ============================================================

for k in lead_vectors:
    lead_vectors[k] = lead_vectors[k] / np.linalg.norm(lead_vectors[k])


# ============================================================
# REFERENCE SPHERE
# ============================================================

phi = np.linspace(0, np.pi, 40)
theta = np.linspace(0, 2*np.pi, 40)
phi, theta = np.meshgrid(phi, theta)

xs = np.sin(phi) * np.cos(theta)
ys = np.sin(phi) * np.sin(theta)
zs = np.cos(phi)

sphere = go.Surface(
    x=xs, y=ys, z=zs,
    opacity=0.08,
    showscale=False,
    colorscale=[[0, "lightgray"], [1, "lightgray"]],
)

# ============================================================
# PLANES
# ============================================================

grid = np.linspace(-1.1, 1.1, 25)

# Frontal plane (Y = 0)
Xf, Zf = np.meshgrid(grid, grid)
Yf = np.zeros_like(Xf)

frontal_plane = go.Surface(
    x=Xf, y=Yf, z=Zf,
    opacity=0.18,
    showscale=False,
    colorscale=[[0, "lightblue"], [1, "lightblue"]],
)

# Horizontal plane (Z = 0)
Xh, Yh = np.meshgrid(grid, grid)
Zh = np.zeros_like(Xh)

horizontal_plane = go.Surface(
    x=Xh, y=Yh, z=Zh,
    opacity=0.18,
    showscale=False,
    colorscale=[[0, "lightgreen"], [1, "lightgreen"]],
)

# ============================================================
# POINTS (LENSES)
# ============================================================

x_limb, y_limb, z_limb, text_limb = [], [], [], []
x_chest, y_chest, z_chest, text_chest = [], [], [], []

for name, vec in lead_vectors.items():
    if name.startswith("V"):
        x_chest.append(vec[0])
        y_chest.append(vec[1])
        z_chest.append(vec[2])
        text_chest.append(name)
    else:
        x_limb.append(vec[0])
        y_limb.append(vec[1])
        z_limb.append(vec[2])
        text_limb.append(name)

limb_points = go.Scatter3d(
    x=x_limb, y=y_limb, z=z_limb,
    mode="markers+text",
    marker=dict(size=7, color="red"),
    text=text_limb,
    textposition="top center",
    name="Limb leads"
)

chest_points = go.Scatter3d(
    x=x_chest, y=y_chest, z=z_chest,
    mode="markers+text",
    marker=dict(size=7, color="blue"),
    text=text_chest,
    textposition="top center",
    name="Precordial leads"
)

heart = go.Scatter3d(
    x=[0], y=[0], z=[0],
    mode="markers+text",
    marker=dict(size=6, color="black"),
    text=["Heart"],
    textposition="bottom center",
    name="Heart"
)

# ============================================================
# AXES
# ============================================================

axis_x = go.Scatter3d(
    x=[0, -1.2], y=[0, 0], z=[0, 0],
    mode="lines+text",
    line=dict(color="red", width=6),
    text=["", "X (Left)"],
    textposition="top center",
    showlegend=False
)

axis_y = go.Scatter3d(
    x=[0, 0], y=[0, 1.2], z=[0, 0],
    mode="lines+text",
    line=dict(color="blue", width=6),
    text=["", "Y (Anterior)"],
    textposition="top center",
    showlegend=False
)

axis_z = go.Scatter3d(
    x=[0, 0], y=[0, 0], z=[0, 1.2],
    mode="lines+text",
    line=dict(color="green", width=6),
    text=["", "Z (Superior)"],
    textposition="top center",
    showlegend=False
)

# ============================================================
# FIGURE
# ============================================================

fig = go.Figure(data=[
    sphere,
    frontal_plane,
    horizontal_plane,
    limb_points,
    chest_points,
    heart,
    axis_x,
    axis_y,
    axis_z
])

fig.update_layout(
    title="Corrected ECG Lead Positions (Z = Height)",
    scene=dict(
        xaxis=dict(title="X (Right-Left)", range=[-1.2, 1.2]),
        yaxis=dict(title="Y (Anterior-Posterior)", range=[-1.2, 1.2]),
        zaxis=dict(title="Z (Superior-Inferior)", range=[-1.2, 1.2]),
        aspectmode="cube"
    ),
    margin=dict(l=0, r=0, b=0, t=50)
)

fig.show()

# ============================================================
# ===================== ECG VECTOR ENGINE ====================
# ============================================================

import numpy as np
import plotly.graph_objects as go
import plotly.subplots as sp

# ----------------------------
# TIME BASE
# ----------------------------
fs = 1000
t = np.linspace(0, 1, fs, endpoint=False)

# ===========================================================
# ================= ECG VECTOR BUILDER (MODLAR) ==============
# ===========================================================

def gaussian(t, mu, sigma, amp=1.0):
    return amp * np.exp(-0.5 * ((t - mu) / sigma) ** 2)

def unit(v):
    v = np.array(v, dtype=float)
    return v / np.linalg.norm(v)

def gate(t, t_start, t_end):
    return ((t >= t_start) & (t <= t_end)).astype(float)

def wave_windowed(t, mu, sigma, amp, direction, t_start, t_end):
    return np.outer(
        gaussian(t, mu, sigma, amp) * gate(t, t_start, t_end),
        unit(direction)
    )

# ============================================================
# COMPONENTS
# ============================================================

def p_wave(t):
    return wave_windowed(
        t, 0.16, 0.018, 0.10,
        [-0.4, 0.3, -0.85],
        0.10, 0.22
    )

def pr_segment(t):
    return np.zeros((len(t), 3))

def qrs_complex(t):
    gain = 0.75

    Q = wave_windowed(
        t, 0.34, 0.010,
        0.08 * gain,
        [0.9, 0.0, 0.1],
        0.30, 0.38
    )

    R = wave_windowed(
        t, 0.38, 0.015,
        1.00 * gain,
        [-0.7, 0.25, -0.65],
        0.34, 0.43
    )

    S = wave_windowed(
        t, 0.42, 0.012,
        0.15 * gain,
        [-0.3, -0.4, 0.7],
        0.38, 0.46
    )

    return Q + R + S

def st_segment(t, elevation=0.0, direction=[-0.2, 0.3, -0.9]):
    return np.outer(elevation * gate(t, 0.44, 0.56), unit(direction))

def t_wave(t):
    return wave_windowed(
        t, 0.70, 0.060, 0.25,
        [-0.6, 0.2, -0.6],
        0.58, 0.86
    )

# ============================================================
# FINAL VECTOR
# ============================================================

def build_vector(t):
    V = np.zeros((len(t), 3))
    V += p_wave(t)
    V += pr_segment(t)
    V += qrs_complex(t)
    V += st_segment(t)
    V += t_wave(t)
    return V

V = build_vector(t)

# ============================================================
# PROJECTION
# ============================================================

ecg = {name: V @ L for name, L in lead_vectors.items()}

# ============================================================
# ESCALA EM mV (QRS ~1 mV)
# ============================================================

target_qrs_mV = 1.0
current_max = max(np.max(np.abs(v)) for v in ecg.values())
scale = target_qrs_mV / current_max

for k in ecg:
    ecg[k] *= scale

# ============================================================
# TEMPO
# ============================================================

t_ms = t * 1000

# ============================================================
# PLOT
# ============================================================

lead_order = [
    "I", "II", "III",
    "aVR", "aVL", "aVF",
    "V1", "V2", "V3",
    "V4", "V5", "V6"
]

fig_ecg = sp.make_subplots(
    rows=6, cols=2,
    subplot_titles= lead_order,
    vertical_spacing=0.04,
    horizontal_spacing = 0.04,
    row_heights=[1]*6
)

row, col = 1, 1

for lead in lead_order:
    fig_ecg.add_trace(
        go.Scatter(x=t_ms, y=ecg[lead], mode="lines", line=dict(width=2)),
        row=row, col=col
    )
    col += 1
    if col > 2:
        col = 1
        row += 1

# ============================================================
# GRID SINCRONIZADO COM EIXO (3 QUADRADÕES)
# ============================================================

y_min, y_max = -1.5, 1.5
x_max = 1200

shapes = []

for i in range(1, 13):
    xref = f"x{i}" if i > 1 else "x"
    yref = f"y{i}" if i > 1 else "y"

    for x in np.arange(0, x_max + 1, 40):
        shapes.append(dict(type="line", x0=x, x1=x, y0=y_min, y1=y_max,
                           xref=xref, yref=yref,
                           line=dict(color="rgba(200,200,200,0.3)", width=1)))

    for x in np.arange(0, x_max + 1, 200):
        shapes.append(dict(type="line", x0=x, x1=x, y0=y_min, y1=y_max,
                           xref=xref, yref=yref,
                           line=dict(color="rgba(200,200,200,0.8)", width=2)))

    for y in np.arange(y_min, y_max + 0.001, 0.1):
        shapes.append(dict(type="line", x0=0, x1=x_max, y0=y, y1=y,
                           xref=xref, yref=yref,
                           line=dict(color="rgba(200,200,200,0.3)", width=1)))

    for y in np.arange(y_min, y_max + 0.001, 0.5):
        shapes.append(dict(type="line", x0=0, x1=x_max, y0=y, y1=y,
                           xref=xref, yref=yref,
                           line=dict(color="rgba(200,200,200,0.8)", width=2)))

# ============================================================
# LAYOUT FINAL
# ============================================================

fig_ecg.update_layout(
    shapes=shapes,
    height=1400,
    width=400,
    title="ECG 12 Leads (Tempo: ms | Amplitude: mV)",
    showlegend=False,
    plot_bgcolor="white",
    margin=dict(l=10, r=10, t=40, b=10)  # 🔥 AQUI
)

fig_ecg.show()

# ============================================================
# ADD ECG VECTOR LOOP TO THE EXISTING CUBE
# ============================================================

# usa V já definido anteriormente
# normaliza apenas para caber visualmente dentro da esfera/cubo
V_norm = V / np.max(np.linalg.norm(V, axis=1))

vec_loop = go.Scatter3d(
    x=V_norm[:, 0],
    y=V_norm[:, 1],
    z=V_norm[:, 2],
    mode="lines",
    line=dict(
        width=6,
        color=np.linspace(0, 1, len(V_norm)),
        colorscale="Turbo"
    ),
    name="ECG vector loop"
)

vec_tip = go.Scatter3d(
    x=[V_norm[-1, 0]],
    y=[V_norm[-1, 1]],
    z=[V_norm[-1, 2]],
    mode="markers",
    marker=dict(size=5, color="black"),
    name="Vector tip"
)

# adiciona ao MESMO fig já existente
fig.add_trace(vec_loop)
fig.add_trace(vec_tip)

# garante que os pontos/textos das derivações continuem visíveis
fig.update_traces(
    selector=dict(name="Limb leads"),
    marker=dict(size=7, color="red"),
    textposition="top center"
)

fig.update_traces(
    selector=dict(name="Precordial leads"),
    marker=dict(size=7, color="blue"),
    textposition="top center"
)

fig.show()

# ============================================================
# 🔥 NOVO: VETOR DE LESÃO (STEMI V1–V2)
# ============================================================

def stemi_v1v2(t, magnitude=0.25):
    st_dir = unit(
        lead_vectors["V1"] + lead_vectors["V2"]
    )

    return np.outer(
        magnitude * gate(t, 0.44, 0.60),
        st_dir
    )

# ============================================================
# FINAL VECTOR
# ============================================================

def build_vector(t):
    V = np.zeros((len(t), 3))
    V += p_wave(t)
    V += pr_segment(t)
    V += qrs_complex(t)
    V += st_segment(t)
    V += t_wave(t)
    return V

# ============================================================
# 🔥 AQUI ESTÁ A MUDANÇA PRINCIPAL
# ============================================================

V = build_vector(t)
V += stemi_v1v2(t, magnitude=0.25)

# ============================================================
# PROJECTION
# ============================================================

ecg = {name: V @ L for name, L in lead_vectors.items()}

# ============================================================
# ESCALA EM mV (QRS ~1 mV)
# ============================================================

target_qrs_mV = 1.0
current_max = max(np.max(np.abs(v)) for v in ecg.values())
scale = target_qrs_mV / current_max

for k in ecg:
    ecg[k] *= scale

# ============================================================
# TEMPO
# ============================================================

t_ms = t * 1000

# ============================================================
# PLOT
# ============================================================

lead_order = [
    "I", "II", "III",
    "aVR", "aVL", "aVF",
    "V1", "V2", "V3",
    "V4", "V5", "V6"
]

fig_ecg = sp.make_subplots(
    rows=6, cols=2,
    subplot_titles=lead_order,
    vertical_spacing=0.04,
    horizontal_spacing=0.04,
    row_heights=[1]*6
)

row, col = 1, 1

for lead in lead_order:
    fig_ecg.add_trace(
        go.Scatter(x=t_ms, y=ecg[lead], mode="lines", line=dict(width=2)),
        row=row, col=col
    )
    col += 1
    if col > 2:
        col = 1
        row += 1

# ============================================================
# GRID
# ============================================================

y_min, y_max = -1.5, 1.5
x_max = 1200

shapes = []

for i in range(1, 13):
    xref = f"x{i}" if i > 1 else "x"
    yref = f"y{i}" if i > 1 else "y"

    for x in np.arange(0, x_max + 1, 40):
        shapes.append(dict(type="line", x0=x, x1=x, y0=y_min, y1=y_max,
                           xref=xref, yref=yref,
                           line=dict(color="rgba(200,200,200,0.3)", width=1)))

    for x in np.arange(0, x_max + 1, 200):
        shapes.append(dict(type="line", x0=x, x1=x, y0=y_min, y1=y_max,
                           xref=xref, yref=yref,
                           line=dict(color="rgba(200,200,200,0.8)", width=2)))

    for y in np.arange(y_min, y_max + 0.001, 0.1):
        shapes.append(dict(type="line", x0=0, x1=x_max, y0=y, y1=y,
                           xref=xref, yref=yref,
                           line=dict(color="rgba(200,200,200,0.3)", width=1)))

    for y in np.arange(y_min, y_max + 0.001, 0.5):
        shapes.append(dict(type="line", x0=0, x1=x_max, y0=y, y1=y,
                           xref=xref, yref=yref,
                           line=dict(color="rgba(200,200,200,0.8)", width=2)))

# ============================================================
# LAYOUT FINAL
# ============================================================

fig_ecg.update_layout(
    shapes=shapes,
    height=1400,
    width=400,
    title="ECG 12 Leads — STEMI V1–V2",
    showlegend=False,
    plot_bgcolor="white",
    margin=dict(l=10, r=10, t=40, b=10)
)

fig_ecg.show()

# ============================================================
# PLOT DO NOVO VETOR (COM STEMI) NO CUBO
# ============================================================

# normaliza para caber no espaço do cubo
V_plot = V / np.max(np.linalg.norm(V, axis=1))

# trajetória completa
vec_loop = go.Scatter3d(
    x=V_plot[:, 0],
    y=V_plot[:, 1],
    z=V_plot[:, 2],
    mode="lines",
    line=dict(
        width=6,
        color=np.linspace(0, 1, len(V_plot)),
        colorscale="Turbo"
    ),
    name="Vector (with STEMI V1-V2)"
)

# ponta do vetor
vec_tip = go.Scatter3d(
    x=[V_plot[-1, 0]],
    y=[V_plot[-1, 1]],
    z=[V_plot[-1, 2]],
    mode="markers",
    marker=dict(size=6, color="black"),
    name="Tip"
)

# adiciona ao cubo existente
fig.add_trace(vec_loop)
fig.add_trace(vec_tip)

# ============================================================
# HYPERACUTE T WAVE (V1–V2) — CORRIGIDO
# ============================================================

def hatw_v1v2(t, magnitude=0.6):
    t_dir = unit(
        lead_vectors["V1"] + lead_vectors["V2"]
    )

    # T wave mais tardia (após J point), larga e alta
    t_mag = gaussian(t, mu=0.55, sigma=0.06, amp=magnitude)

    # 🔥 janela estrita (evita elevar ST)
    window = gate(t, 0.50, 0.80)

    return np.outer(t_mag * window, t_dir)

# ============================================================
# FINAL VECTOR
# ============================================================

def build_vector(t):
    V = np.zeros((len(t), 3))
    V += p_wave(t)
    V += pr_segment(t)
    V += qrs_complex(t)
    V += st_segment(t)        # mantém baseline
    V += hatw_v1v2(t)         # 🔥 substitui T wave normal
    return V

# ============================================================
# PIPELINE PRINCIPAL
# ============================================================

V = build_vector(t)

# ============================================================
# PROJECTION
# ============================================================

ecg = {name: V @ L for name, L in lead_vectors.items()}

# ============================================================
# ESCALA EM mV (QRS ~1 mV)
# ============================================================

target_qrs_mV = 1.0
current_max = max(np.max(np.abs(v)) for v in ecg.values())
scale = target_qrs_mV / current_max

for k in ecg:
    ecg[k] *= scale

# ============================================================
# TEMPO
# ============================================================

t_ms = t * 1000

# ============================================================
# PLOT
# ============================================================

lead_order = [
    "I", "II", "III",
    "aVR", "aVL", "aVF",
    "V1", "V2", "V3",
    "V4", "V5", "V6"
]

fig_ecg = sp.make_subplots(
    rows=6, cols=2,
    subplot_titles=lead_order,
    vertical_spacing=0.04,
    horizontal_spacing=0.04,
    row_heights=[1]*6
)

row, col = 1, 1

for lead in lead_order:
    fig_ecg.add_trace(
        go.Scatter(x=t_ms, y=ecg[lead], mode="lines", line=dict(width=2)),
        row=row, col=col
    )
    col += 1
    if col > 2:
        col = 1
        row += 1

# ============================================================
# GRID
# ============================================================

y_min, y_max = -1.5, 1.5
x_max = 1200

shapes = []

for i in range(1, 13):
    xref = f"x{i}" if i > 1 else "x"
    yref = f"y{i}" if i > 1 else "y"

    for x in np.arange(0, x_max + 1, 40):
        shapes.append(dict(type="line", x0=x, x1=x, y0=y_min, y1=y_max,
                           xref=xref, yref=yref,
                           line=dict(color="rgba(200,200,200,0.3)", width=1)))

    for x in np.arange(0, x_max + 1, 200):
        shapes.append(dict(type="line", x0=x, x1=x, y0=y_min, y1=y_max,
                           xref=xref, yref=yref,
                           line=dict(color="rgba(200,200,200,0.8)", width=2)))

    for y in np.arange(y_min, y_max + 0.001, 0.1):
        shapes.append(dict(type="line", x0=0, x1=x_max, y0=y, y1=y,
                           xref=xref, yref=yref,
                           line=dict(color="rgba(200,200,200,0.3)", width=1)))

    for y in np.arange(y_min, y_max + 0.001, 0.5):
        shapes.append(dict(type="line", x0=0, x1=x_max, y0=y, y1=y,
                           xref=xref, yref=yref,
                           line=dict(color="rgba(200,200,200,0.8)", width=2)))

# ============================================================
# LAYOUT FINAL
# ============================================================

fig_ecg.update_layout(
    shapes=shapes,
    height=1400,
    width=400,
    title="ECG 12 Leads — HATW V1–V2 (Corrected)",
    showlegend=False,
    plot_bgcolor="white",
    margin=dict(l=10, r=10, t=40, b=10)
)

fig_ecg.show()

# ============================================================
# PLOT DO NOVO VETOR (COM HATW) NO CUBO
# ============================================================

# normaliza para caber no cubo
V_plot = V / np.max(np.linalg.norm(V, axis=1))

# remove loops antigos (opcional, mas recomendado)
fig.data = tuple(
    t for t in fig.data
    if getattr(t, "name", "") not in ["Vector (HATW V1-V2)", "Tip HATW"]
)

# trajetória do vetor (loop completo)
vec_loop_hatw = go.Scatter3d(
    x=V_plot[:, 0],
    y=V_plot[:, 1],
    z=V_plot[:, 2],
    mode="lines",
    line=dict(
        width=6,
        color=np.linspace(0, 1, len(V_plot)),
        colorscale="Turbo"
    ),
    name="Vector (HATW V1-V2)"
)

# ponta do vetor (último instante)
vec_tip_hatw = go.Scatter3d(
    x=[V_plot[-1, 0]],
    y=[V_plot[-1, 1]],
    z=[V_plot[-1, 2]],
    mode="markers",
    marker=dict(size=6, color="black"),
    name="Tip HATW"
)

# adiciona ao cubo existente
fig.add_trace(vec_loop_hatw)
fig.add_trace(vec_tip_hatw)

fig.show()

!pip install plotly

import numpy as np
import plotly.graph_objects as go

# ============================================================
# LEADS
# ============================================================

def frontal_lead(angle_deg):
    a = np.deg2rad(angle_deg)
    return np.array([-np.cos(a), 0.0, np.sin(a)])

def chest_lead(x, y, z):
    v = np.array([x, y, z], dtype=float)
    return v / np.linalg.norm(v)

def mirror_right(vec):
    x, y, z = vec
    return np.array([-x, y, z], dtype=float)

# ============================================================
# LIMB LEADS (HEXAXIAL SYSTEM)
# ============================================================

lead_vectors = {
    "I":   frontal_lead(0),
    "II":  frontal_lead(-60),
    "III": frontal_lead(-120),
    "aVF": frontal_lead(-90),
    "aVL": frontal_lead(30),   # ✅ correto
    "aVR": frontal_lead(150),  # ✅ correto
}

# ============================================================
# PRECORDIAL LEADS (EXPANDED, ANATOMIC FRAME)
# X: direita (+) / esquerda (-)
# Y: anterior (+) / posterior (-)
# Z: superior (+) / inferior (-)
# ============================================================

precordial_vectors = {
    # clássicos (mantidos)
    "V1": chest_lead(0.55, 0.85,  0.05),
    "V2": chest_lead(0.35, 0.90,  0.05),
    "V3": chest_lead(0.10, 0.95,  0.00),
    "V4": chest_lead(-0.20, 0.95, -0.05),
    "V5": chest_lead(-0.45, 0.85, -0.05),
    "V6": chest_lead(-0.65, 0.75,  0.00),

    # 🔴 direitas (reposicionadas — mais laterais que V1
    "V3R": chest_lead(0.60, 0.60, 0.0),
    "V4R": chest_lead(0.70, 0.50, -0.05),

    # 🔵 posteriores (idealmente com componente posterior real: Y < 0)
    "V7": chest_lead(-0.75, -0.20, 0.00),
    "V8": chest_lead(-0.70, -0.45, 0.00),
    "V9": chest_lead(-0.60, -0.65, 0.00),
}

lead_vectors.update(precordial_vectors)

# normalização
for k in lead_vectors:
    lead_vectors[k] = lead_vectors[k] / np.linalg.norm(lead_vectors[k])

# ============================================================
# ESFERA + PLANOS
# ============================================================

phi = np.linspace(0, np.pi, 40)
theta = np.linspace(0, 2*np.pi, 40)
phi, theta = np.meshgrid(phi, theta)

xs = np.sin(phi) * np.cos(theta)
ys = np.sin(phi) * np.sin(theta)
zs = np.cos(phi)

sphere = go.Surface(x=xs, y=ys, z=zs, opacity=0.08, showscale=False)

grid = np.linspace(-1.1, 1.1, 25)

# frontal
Xf, Zf = np.meshgrid(grid, grid)
Yf = np.zeros_like(Xf)
frontal_plane = go.Surface(x=Xf, y=Yf, z=Zf, opacity=0.18, showscale=False)

# horizontal
Xh, Yh = np.meshgrid(grid, grid)
Zh = np.zeros_like(Xh)
horizontal_plane = go.Surface(x=Xh, y=Yh, z=Zh, opacity=0.18, showscale=False)

# ============================================================
# PONTOS (LEADS)
# ============================================================

x_limb, y_limb, z_limb, text_limb = [], [], [], []
x_chest, y_chest, z_chest, text_chest = [], [], [], []

for name, vec in lead_vectors.items():
    if name.startswith("V"):
        x_chest.append(vec[0])
        y_chest.append(vec[1])
        z_chest.append(vec[2])
        text_chest.append(name)
    else:
        x_limb.append(vec[0])
        y_limb.append(vec[1])
        z_limb.append(vec[2])
        text_limb.append(name)

limb_points = go.Scatter3d(
    x=x_limb, y=y_limb, z=z_limb,
    mode="markers+text",
    marker=dict(size=7, color="red"),
    text=text_limb,
    textposition="top center",
    name="Limb Leads"
)

chest_points = go.Scatter3d(
    x=x_chest, y=y_chest, z=z_chest,
    mode="markers+text",
    marker=dict(size=7, color="blue"),
    text=text_chest,
    textposition="top center",
    name="Precordial Leads"
)

heart = go.Scatter3d(
    x=[0], y=[0], z=[0],
    mode="markers",
    marker=dict(size=6, color="black"),
    name="Heart"
)

# ============================================================
# FIGURA BASE (CUBO FIXO)
# ============================================================

fig = go.Figure(data=[
    sphere,
    frontal_plane,
    horizontal_plane,
    limb_points,
    chest_points,
    heart
])

fig.update_layout(
    title="ECG Vector Space",
    scene=dict(
        xaxis=dict(range=[-1.2, 1.2], title="X (Right + / Left -)"),
        yaxis=dict(range=[-1.2, 1.2], title="Y (Anterior + / Posterior -)"),
        zaxis=dict(range=[-1.2, 1.2], title="Z (Superior + / Inferior -)"),
        aspectmode="cube"
    )
)

# ============================================================
# FUNÇÃO: ADICIONAR VETOR (SEM APAGAR CUBO)
# ============================================================

def add_vector(vec):
    fig.data = tuple(t for t in fig.data if t.name != "Vector")

    vector_trace = go.Scatter3d(
        x=[0, vec[0]],
        y=[0, vec[1]],
        z=[0, vec[2]],
        mode="lines+markers",
        line=dict(width=8, color="black"),
        marker=dict(size=5),
        name="Vector"
    )

    fig.add_trace(vector_trace)

fig.show()

# ============================================================
# DEPENDÊNCIAS
# ============================================================
import ipywidgets as widgets
from IPython.display import display
import numpy as np

# ============================================================
# ESTADO GLOBAL (VETOR)
# ============================================================

current_vector = np.array([0.0, 0.0, 0.0])

# ============================================================
# SLIDERS
# ============================================================

sx = widgets.FloatSlider(min=-1, max=1, step=0.05, value=0, description='X')
sy = widgets.FloatSlider(min=-1, max=1, step=0.05, value=0, description='Y')
sz = widgets.FloatSlider(min=-1, max=1, step=0.05, value=0, description='Z')

# ============================================================
# ATUALIZAÇÃO DO ESTADO (SEM PLOT)
# ============================================================

def update_state(_=None):
    global current_vector
    current_vector = np.array([sx.value, sy.value, sz.value])

sx.observe(update_state, names='value')
sy.observe(update_state, names='value')
sz.observe(update_state, names='value')

# inicializa
update_state()

# ============================================================
# DISPLAY
# ============================================================

display(widgets.VBox([sx, sy, sz]))

import numpy as np
import plotly.graph_objects as go

# ============================================================
# FIGURA BASE
# ============================================================

fig = go.Figure()

sphere.opacity = 0.04
fig.add_trace(sphere)

fig.add_trace(limb_points)
fig.add_trace(chest_points)

fig.update_layout(
    title=dict(text="ECG Vector Space", x=0.5),
    scene=dict(
        xaxis=dict(range=[-1.2,1.2]),
        yaxis=dict(range=[-1.2,1.2]),
        zaxis=dict(range=[-1.2,1.2]),
        aspectmode="cube",
        camera=dict(eye=dict(x=1.55, y=1.55, z=1.15))
    ),
    paper_bgcolor="white",
    plot_bgcolor="white",
    margin=dict(l=10, r=10, t=50, b=10)
)

# ============================================================
# BULLSEYE
# ============================================================

def add_bullseye(vec, angles_basal, angles_mid, angles_apical):

    global fig

    fig.data = tuple(
        t for t in fig.data
        if getattr(t, "name", None) not in ("Bullseye", "Damage")
    )

    # =========================================================
    # GRID FIXO (ANATOMIA)
    # =========================================================

    theta = np.linspace(0, 2*np.pi, 360)
    r = np.linspace(0, 1, 160)

    T, R = np.meshgrid(theta, r)

    # 🔥 orientação fixa (hexaxial aproximado)
    rotation_offset = np.deg2rad(-30)
    T = np.mod(T + rotation_offset, 2*np.pi)

    scale = 0.9
    X = scale * R * np.cos(T)
    Y = scale * R * np.sin(T)

    # =========================================================
    # GEOMETRIA DO CONE
    # =========================================================

    z_basal, z_mid, z_apical = 0.25, -0.25, -0.90

    slope1 = (z_mid - z_apical) / 0.40
    slope2 = (z_basal - z_mid) / 0.30

    Z = np.zeros_like(R)

    Z[R < 0.40] = z_apical + slope1 * R[R < 0.40]
    Z[(R >= 0.40) & (R < 0.70)] = z_mid + slope2 * (R[(R >= 0.40) & (R < 0.70)] - 0.40)
    Z[R >= 0.70] = z_basal + slope2 * (R[R >= 0.70] - 0.70)

    # =========================================================
    # 🔥 MAPA DE DANO (FISIOLOGICAMENTE MELHOR)
    # =========================================================

    vec = np.array(vec, dtype=float)
    norm = np.linalg.norm(vec)

    if norm > 1e-6:
        v = -vec / norm

        # -------------------------
        # ÂNGULO NO PLANO FRONTAL
        # -------------------------
        theta_vec = np.arctan2(v[1], -v[0])

        # diferença angular
        dtheta = np.angle(np.exp(1j*(T - theta_vec)))

        # largura angular do dano
        sigma_theta = 0.5
        angular_component = np.exp(-(dtheta**2)/(2*sigma_theta**2))

        # -------------------------
        # COMPONENTE APICALIDADE
        # -------------------------
        # z positivo = basal, negativo = apical

        z_norm = (Z - Z.min()) / (Z.max() - Z.min())

        # vetor aponta para cima/baixo
        apical_bias = (1 - v[2]) / 2  # 0 basal → 1 apical

        sigma_z = 0.25
        radial_component = np.exp(-((z_norm - apical_bias)**2)/(2*sigma_z**2))

        # -------------------------
        # COMBINAÇÃO FINAL
        # -------------------------
        Z_damage = angular_component * radial_component
        Z_damage /= (Z_damage.max() + 1e-6)

        mask_damage = Z_damage > 0.55

    else:
        mask_damage = np.zeros_like(Z, dtype=bool)

    # =========================================================
    # SEGMENTAÇÃO
    # =========================================================

    colors = [
        "#8FAADC","#F6BD60","#F28482","#84A59D","#90BE6D","#F7EDE2",
        "#CDB4DB","#FFC8DD","#B5838D","#A0C4FF","#BDB2FF","#FFD6A5",
        "#CAFFBF","#FFADAD","#D0F4DE","#FDFFB6","#9BF6FF"
    ]

    segment_id = 0

    def angle_mask(a0, a1):
        if a1 < a0:
            return (T >= a0) | (T < a1)
        return (T >= a0) & (T < a1)

    def add_segment(r0, r1, angles):
        nonlocal segment_id

        for i in range(len(angles)):
            a0 = angles[i]
            a1 = angles[(i+1) % len(angles)]

            mask = (R >= r0) & (R < r1) & angle_mask(a0, a1)

            fig.add_trace(go.Surface(
                x=np.where(mask, X, np.nan),
                y=np.where(mask, Y, np.nan),
                z=np.where(mask, Z, np.nan),
                surfacecolor=np.ones_like(Z),
                colorscale=[[0, colors[segment_id]], [1, colors[segment_id]]],
                opacity=0.55,
                showscale=False,
                name="Bullseye"
            ))

            segment_id += 1

    add_segment(0.70,1.00,angles_basal)
    add_segment(0.40,0.70,angles_mid)
    add_segment(0.18,0.40,angles_apical)

    # apex
    fig.add_trace(go.Surface(
        x=np.where(R < 0.18, X, np.nan),
        y=np.where(R < 0.18, Y, np.nan),
        z=np.where(R < 0.18, Z, np.nan),
        surfacecolor=np.ones_like(Z),
        colorscale=[[0, colors[16]], [1, colors[16]]],
        opacity=0.55,
        showscale=False,
        name="Bullseye"
    ))

    # =========================================================
    # 🔥 DANO (overlay branco)
    # =========================================================

    fig.add_trace(go.Surface(
        x=np.where(mask_damage, X, np.nan),
        y=np.where(mask_damage, Y, np.nan),
        z=np.where(mask_damage, Z + 0.02, np.nan),
        surfacecolor=np.ones_like(Z),
        colorscale=[[0, "white"], [1, "white"]],
        opacity=0.9,
        showscale=False,
        name="Damage"
    ))

    # =========================================================
    # CONTORNOS + RADIAIS
    # =========================================================

    theta_lines = np.linspace(0,2*np.pi,500)

    def z_func(rval):
        if rval < 0.40:
            return z_apical + slope1 * rval
        elif rval < 0.70:
            return z_mid + slope2 * (rval - 0.40)
        return z_basal + slope2 * (rval - 0.70)

    for r_line, w in [(0.18,5),(0.40,5),(0.70,5),(1.00,6)]:
        z_val = z_func(r_line)
        fig.add_trace(go.Scatter3d(
            x=scale*r_line*np.cos(theta_lines),
            y=scale*r_line*np.sin(theta_lines),
            z=[z_val]*len(theta_lines),
            mode="lines",
            line=dict(color="black", width=w),
            showlegend=False
        ))

    def draw_radials(r0, r1, angles):
        for ang in angles:
            fig.add_trace(go.Scatter3d(
                x=[scale*r0*np.cos(ang), scale*r1*np.cos(ang)],
                y=[scale*r0*np.sin(ang), scale*r1*np.sin(ang)],
                z=[z_func(r0), z_func(r1)],
                mode="lines",
                line=dict(color="black", width=3),
                showlegend=False
            ))

    draw_radials(0.70,1.00,angles_basal)
    draw_radials(0.40,0.70,angles_mid)
    draw_radials(0.18,0.40,angles_apical)

# ============================================================
# VETOR
# ============================================================

def add_vector(vec):
    global fig

    fig.data = tuple(t for t in fig.data if t.name != "Vector")

    fig.add_trace(go.Scatter3d(
        x=[0, vec[0]],
        y=[0, vec[1]],
        z=[0, vec[2]],
        mode="lines+markers",
        line=dict(width=8, color="black"),
        marker=dict(size=5),
        name="Vector"
    ))

# ============================================================
# EXECUÇÃO
# ============================================================

angles_basal = np.deg2rad([0,60,120,180,240,300])
angles_mid   = np.deg2rad([0,60,120,180,240,300])
angles_apical= np.deg2rad([45,135,225,315])

add_vector(current_vector)
add_bullseye(current_vector, angles_basal, angles_mid, angles_apical)

fig.show()

# ============================================================
# 🔥 FUNÇÃO: BARPLOT
# ============================================================

def plot_projection(vec):
    names = list(lead_vectors.keys())
    values = np.array([np.dot(vec, lead_vectors[l]) for l in names])

    colors = ["red" if v > 0 else "blue" for v in values]

    bar_fig = go.Figure()

    bar_fig.add_bar(
        x=names,
        y=values,
        marker_color=colors,
        text=[f"{v:.2f}" for v in values],
        textposition="outside"
    )

    bar_fig.add_scatter(
        x=names,
        y=[0]*len(values),
        mode="lines",
        line=dict(dash="dash")
    )

    bar_fig.update_layout(
        title="Projeção nas derivações",
        yaxis=dict(range=[-1,1])
    )

    bar_fig.show()

# ============================================================
# 🔥 EXEMPLO DE USO
# ============================================================

# vetor arbitrário (substitua pelo current_vector)
vec = current_vector

plot_projection(vec)

# ============================================================
# PROJEÇÃO DO VETOR NAS DERIVAÇÕES
# ============================================================

def project_vector(vec):
    return {lead: np.dot(vec, lead_vectors[lead]) for lead in lead_vectors}


# ============================================================
# GRUPOS BASE (SEM V3R/V4R/V7-9)
# ============================================================

contiguous_groups_base = [
    ["II", "III", "aVF"],

    ["I", "aVL"],
    ["V5", "V6"],

    ["V1", "V2"],
    ["V2", "V3", "V4"],
]


# ============================================================
# GRUPOS COMPLETOS (COM V3R/V4R/V7-9)
# ============================================================

contiguous_groups_full = [
    ["II", "III", "aVF"],

    ["I", "aVL"],
    ["V5", "V6"],
    ["V7", "V8", "V9"],

    ["V1", "V2"],
    ["V2", "V3", "V4"],

    ["V3R", "V4R"],

    ["V7", "V8", "V9", "V5", "V6"],
]


# ============================================================
# CRITÉRIO DE STEMI (GENERALIZADO)
# ============================================================

def is_stemi(vec, groups, threshold=0.25):
    proj = project_vector(vec)

    for group in groups:
        count = sum(proj[l] > threshold for l in group)
        if count >= 2:
            return True

    return False


# ============================================================
# CAMPO ESCALAR CONTÍNUO
# ============================================================

def generate_scalar_field(groups, resolution=35, max_radius=1.0, threshold=0.25):

    xs = np.linspace(-max_radius, max_radius, resolution)
    ys = np.linspace(-max_radius, max_radius, resolution)
    zs = np.linspace(-max_radius, max_radius, resolution)

    X, Y, Z = np.meshgrid(xs, ys, zs, indexing="ij")
    values = np.zeros_like(X)

    for i in range(resolution):
        for j in range(resolution):
            for k in range(resolution):

                vec = np.array([X[i, j, k], Y[i, j, k], Z[i, j, k]])
                r = np.linalg.norm(vec)

                if r == 0 or r > max_radius:
                    continue

                values[i, j, k] = 1 if is_stemi(vec, groups, threshold) else 0

    return X, Y, Z, values


# ============================================================
# PLOT: BASE + FULL + EXTRA
# ============================================================

def plot_stemi_solid(resolution=35, threshold=0.25):

    global fig

    # remove sólidos anteriores
    fig.data = tuple(
        t for t in fig.data
        if t.name not in ["BASE", "FULL", "EXTRA"]
    )

    # gera campos
    X, Y, Z, base = generate_scalar_field(contiguous_groups_base, resolution, 1.0, threshold)
    _, _, _, full = generate_scalar_field(contiguous_groups_full, resolution, 1.0, threshold)

    # diferença: o que só aparece com derivações adicionais
    extra = np.logical_and(full == 1, base == 0).astype(float)

    # ============================================================
    # 🔵 BASE (ECG padrão)
    # ============================================================
    fig.add_trace(go.Isosurface(
        x=X.flatten(),
        y=Y.flatten(),
        z=Z.flatten(),
        value=base.flatten(),

        isomin=0.5,
        isomax=1.0,
        surface_count=1,

        opacity=0.5,
        colorscale="Blues",

        caps=dict(x_show=False, y_show=False, z_show=False),

        name="BASE"
    ))

    # ============================================================
    # 🟢 FULL (com V3R/V4R/V7-9)
    # ============================================================
    fig.add_trace(go.Isosurface(
        x=X.flatten(),
        y=Y.flatten(),
        z=Z.flatten(),
        value=full.flatten(),

        isomin=0.5,
        isomax=1.0,
        surface_count=1,

        opacity=1,
        colorscale="Greens",

        caps=dict(x_show=False, y_show=False, z_show=False),

        name="FULL"
    ))

    # ============================================================
    # 🔴 EXTRA (novo espaço diagnóstico)
    # ============================================================
    fig.add_trace(go.Isosurface(
        x=X.flatten(),
        y=Y.flatten(),
        z=Z.flatten(),
        value=extra.flatten(),

        isomin=0.5,
        isomax=1.0,
        surface_count=1,

        opacity=1,
        colorscale="Reds",

        caps=dict(x_show=False, y_show=False, z_show=False),

        name="EXTRA"
    ))


def add_ground_bullseye(vec, z_plane=-1.2):

    global fig

    # remove versões anteriores
    fig.data = tuple(
        t for t in fig.data
        if t.name not in ["GROUND_BULLSEYE", "GROUND_LABELS"]
    )

    # =========================================================
    # GRID POLAR
    # =========================================================

    theta = np.linspace(0, 2*np.pi, 300)
    r = np.linspace(0, 1, 120)

    T, R = np.meshgrid(theta, r)

    scale = 0.9

    X = scale * R * np.cos(T)
    Y = scale * R * np.sin(T)
    Z = np.full_like(X, z_plane)

    # =========================================================
    # NORMAL DO PLANO (para iluminação)
    # =========================================================

    normal = np.array([0, 0, 1])  # plano horizontal

    vec = np.array(vec, dtype=float)
    norm = np.linalg.norm(vec)

    if norm > 1e-6:
        v = vec / norm
        intensity = np.dot(normal, v)

        # projeção angular no plano
        vec_proj = np.array([v[0], v[1], 0])
        proj_norm = np.linalg.norm(vec_proj)

        if proj_norm > 1e-6:
            vec_proj /= proj_norm
            theta_vec = np.arctan2(vec_proj[1], vec_proj[0])
        else:
            theta_vec = 0

        dtheta = np.angle(np.exp(1j * (T - theta_vec)))

        sigma = 0.5
        Z_heat = np.exp(-(dtheta**2)/(2*sigma**2))

        # modula pela incidência
        Z_heat *= max(0, intensity)

    else:
        Z_heat = np.zeros_like(X)

    # =========================================================
    # SUPERFÍCIE (heatmap branco)
    # =========================================================

    fig.add_trace(go.Surface(
        x=X,
        y=Y,
        z=Z,
        surfacecolor=Z_heat,
        colorscale=[[0, "rgba(0,0,0,0)"], [1, "white"]],
        showscale=False,
        opacity=1.0,
        name="GROUND_BULLSEYE"
    ))

    # =========================================================
    # SEGMENTAÇÃO AHA
    # =========================================================

    rings = [0.18, 0.40, 0.70, 1.00]

    angles_basal = np.deg2rad([0, 60, 120, 180, 240, 300])
    angles_mid   = np.deg2rad([0, 60, 120, 180, 240, 300])
    angles_apical= np.deg2rad([45, 135, 225, 315])

    # círculos
    theta_lines = np.linspace(0, 2*np.pi, 400)

    for r_line in rings:
        fig.add_trace(go.Scatter3d(
            x=scale * r_line * np.cos(theta_lines),
            y=scale * r_line * np.sin(theta_lines),
            z=[z_plane]*len(theta_lines),
            mode="lines",
            line=dict(color="black", width=3),
            showlegend=False
        ))

    # radiais
    def draw_radials(r0, r1, angles):
        for ang in angles:
            fig.add_trace(go.Scatter3d(
                x=[scale*r0*np.cos(ang), scale*r1*np.cos(ang)],
                y=[scale*r0*np.sin(ang), scale*r1*np.sin(ang)],
                z=[z_plane, z_plane],
                mode="lines",
                line=dict(color="black", width=2),
                showlegend=False
            ))

    draw_radials(0.70, 1.00, angles_basal)
    draw_radials(0.40, 0.70, angles_mid)
    draw_radials(0.18, 0.40, angles_apical)


# ============================================================
# EXECUÇÃO
# ============================================================

plot_stemi_solid(resolution=35, threshold=0.25)
add_vector(current_vector)
add_ground_bullseye(current_vector)

fig.show()

# ============================================================
# IMPORTS
# ============================================================

import numpy as np
import matplotlib.pyplot as plt


# ============================================================
# CAMPO 2D EM UM PLANO
# ============================================================

def generate_2d_plane(plane="frontal", resolution=600, max_radius=1.0, threshold=0.25):
    """
    plane = 'frontal'    -> Y = 0, retorna grade em X-Z
    plane = 'horizontal' -> Z = 0, retorna grade em X-Y
    """

    a = np.linspace(-max_radius, max_radius, resolution)
    b = np.linspace(-max_radius, max_radius, resolution)
    A, B = np.meshgrid(a, b)

    mask = np.full_like(A, np.nan, dtype=float)

    for i in range(resolution):
        for j in range(resolution):

            if plane == "frontal":
                x = A[i, j]
                y = 0.0
                z = B[i, j]
            elif plane == "horizontal":
                x = A[i, j]
                y = B[i, j]
                z = 0.0
            else:
                raise ValueError("plane must be 'frontal' or 'horizontal'")

            vec = np.array([x, y, z], dtype=float)
            r = np.linalg.norm(vec)

            # restringe à seção circular da esfera
            if r == 0 or r > max_radius:
                continue

            mask[i, j] = 1.0 if is_stemi(vec, threshold=threshold) else 0.0

    return A, B, mask


# ============================================================
# FIGURA PUBLICÁVEL EM DOIS PLANOS
# ============================================================

def plot_stemi_2d_publication(resolution=600, max_radius=1.0, threshold=0.25,
                              savepath=None, dpi=600):
    """
    Gera figura 2D publicável com dois painéis:
      A) plano frontal   (X vs Z, Y=0)
      B) plano horizontal (X vs Y, Z=0)
    """

    Xf, Zf, Mf = generate_2d_plane(
        plane="frontal",
        resolution=resolution,
        max_radius=max_radius,
        threshold=threshold
    )

    Xh, Yh, Mh = generate_2d_plane(
        plane="horizontal",
        resolution=resolution,
        max_radius=max_radius,
        threshold=threshold
    )

    fig, axes = plt.subplots(1, 2, figsize=(10, 5), constrained_layout=True)

    panels = [
        (axes[0], Xf, Zf, Mf, "Frontal plane (Y = 0)", "X (Right–Left)", "Z (Superior–Inferior)"),
        (axes[1], Xh, Yh, Mh, "Horizontal plane (Z = 0)", "X (Right–Left)", "Y (Anterior–Posterior)")
    ]

    for ax, A, B, M, title, xlabel, ylabel in panels:
        # região positiva
        ax.contourf(
            A, B, M,
            levels=[0.5, 1.5],
            alpha=0.9
        )

        # borda da região STEMI
        ax.contour(
            A, B, M,
            levels=[0.5],
            linewidths=1.5
        )

        # borda da esfera seccionada
        circle = plt.Circle((0, 0), max_radius, fill=False, linewidth=1.0)
        ax.add_patch(circle)

        # eixos centrais
        ax.axhline(0, linewidth=0.8)
        ax.axvline(0, linewidth=0.8)

        ax.set_title(title, fontsize=11)
        ax.set_xlabel(xlabel, fontsize=10)
        ax.set_ylabel(ylabel, fontsize=10)

        ax.set_aspect("equal")
        ax.set_xlim(-max_radius, max_radius)
        ax.set_ylim(-max_radius, max_radius)

    if savepath is not None:
        plt.savefig(savepath, dpi=dpi, bbox_inches="tight")

    plt.show()


# ============================================================
# EXECUÇÃO
# ============================================================

plot_stemi_2d_publication(
    resolution=700,
    max_radius=1.0,
    threshold=0.25,
    savepath="stemi_two_planes.png",
    dpi=600
)

